# Generated by Django 5.1.1 on 2024-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0003_alter_userstock_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='_id',
            field=models.PositiveIntegerField(default=2179, unique=True),
        ),
    ]
