# Generated by Django 5.1.1 on 2024-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0007_alter_userstock_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='custom_id',
            field=models.PositiveIntegerField(default=9876, unique=True),
        ),
    ]
